---
title: "Final Project - cleaning data"
author: "Yoolim Jin, 22612692"
date: "2015년 11월 23일"
output: html_document
---
Cleaning data for World Bank
```{r, eval = TRUE}

```
Function for cleaning data for Google Files
```{r, eval = TRUE}
clean_data <- function(x, directory = "/Users/Yoolim_Jin/Desktop/Final_Project/clean/") {
  raw <- read.table(x, skip = 4, fill = TRUE, sep = ',', header = TRUE)
  raw1 <- raw[1:grep("Top subregion", raw$Week) - 1, ]
  split_dates <- function(y) {
    return(matrix(unlist(strsplit(y, ' - ')), ncol = 2, byrow = TRUE))
  }
  raw1$Week <- as.character(raw1$Week)
  a <- as.data.frame(split_dates(raw1$Week))
  newdf <- cbind(a, as.numeric(raw1[, 2]))
  names(newdf) <- c('from', 'to', names(raw1)[2])
  newdf$from <- as.Date(newdf$from)
  newdf$to <- as.Date(newdf$to)
  newdf$from_year <- as.numeric(format(newdf$from, format = '%Y'))
  newdf$to_year <- as.numeric(format(newdf$to, format = '%Y'))
  newdf$from_month <- as.numeric(format(newdf$from, format = '%m'))
  newdf$to_month <- as.numeric(format(newdf$to, format = '%m'))
  newdf$from_day <- as.numeric(format(newdf$from, format = '%d'))
  newdf$to_day <- as.numeric(format(newdf$to, format = '%d'))
  write.csv(newdf, paste0(directory, "/clean_", x))
} 
```
Cleaning data for Google Files(unemployment)
```{r}
setwd("/Users/Yoolim_Jin/Desktop/Final_Project/raw/google/inflation")
inf_wd <- "/Users/Yoolim_Jin/Desktop/Final_Project/clean/google/inflation"
clean_data('inf_Nigeria.csv', directory = inf_wd)
clean_data('inf_Canada.csv', directory = inf_wd)
clean_data('inf_South_Africa.csv', directory = inf_wd)
clean_data('inf_US.csv', directory = inf_wd)
```
Cleaning data for Google Files(unemployment)
```{r}
setwd("/Users/Yoolim_Jin/Desktop/Final_Project/raw/google/unemployment")
emp_wd <- "/Users/Yoolim_Jin/Desktop/Final_Project/clean/google/unemployment"
clean_data('unemp_Canada.csv', directory = emp_wd)
clean_data('unemp_Nigeria.csv', directory = emp_wd)
clean_data('unemp_South_Africa.csv', directory = emp_wd)
clean_data('unemp_US.csv', directory = emp_wd)
```
Complete function for taking the weighted average of relative frequency per year
```{r}
rel_freq <- function(file) { #x is the clean data_frame file
  x <- read.csv(file)
  y <- NULL
  for (i in 2006:2013) {
    a <- which(x$from_year == i & x$to_year == i)
    b <- NULL
    for (j in 1:length(a)) {
      b[j] <- x[a[j], 'inflation']
    } 
    sum1 <- sum(b*7)
    c <- setdiff(which(x$from_year == i | x$to_year == i), a)
    d <- NULL
    for (k in 1:length(c)) {
      if(x[c[k], 'from_year'] == i) {
        d[k] <- (31 - x[c[k], 'from_day'] + 1) * x[c[k], 'inflation']
      } else if(x[c[k], 'to_year'] == i) {
        d[k] <- x[c[k], 'from_day'] * x[c[k], 'inflation']
      }
    } 
    sum2 <- sum(d)
    e <- as.numeric(as.Date(paste(i, 12, 31, sep = '-')) - as.Date(paste(i, 1, 1, sep = '-')) + 1)
    y[i - 2005] <- (sum1 + sum2)/e
  } 
  names(y) <- 2006:2013
  return(y)
}
rel_freq('clean_Nigeria.csv')
rel_freq('clean_Canada.csv')
rel_freq('clean_South_Africa.csv')
```

